# Generated by Django 4.0.4 on 2022-05-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=('male', 'male'), max_length=7)),
                ('dob', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('base.baseuser',),
        ),
    ]
