# Generated by Django 4.0.4 on 2022-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_dob_alter_usermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
