# Generated by Django 4.0.4 on 2022-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usermodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='alcoholic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='smoking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
