# Generated by Django 4.0.4 on 2022-05-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bpd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='bps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cardio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ecg',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='app.usermodel'),
        ),
    ]
