# Generated by Django 4.0.4 on 2022-05-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userdata_bpd_userdata_bps_userdata_cardio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='bpd',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='bps',
        ),
        migrations.AddField(
            model_name='userdata',
            name='glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ecg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
